# ELASTICNET REGRESSION

In [2]:
import numpy as np 
import pandas as pd 
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt 
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV

In [3]:
df = pd.read_csv("verisetleri\Hitters.csv")
df = df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [4]:
enet_model = ElasticNet().fit(X_train, y_train)

In [5]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [6]:
enet_model.intercept_

-6.465955602111876

In [7]:
# Tahmin
enet_model.predict(X_train)[0:10]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566, 997.76095723,  99.78828622, 311.33763086,
       418.50335021, 879.9502608 ])

In [8]:
enet_model.predict(X_test)[0:10]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123])

In [9]:
y_pred = enet_model.predict(X_test)

In [10]:
np.sqrt(mean_squared_error(y_test, y_pred))

357.1676548181244

In [11]:
r2_score(y_test, y_pred)

0.41070222469326934

### Model Tunning 

In [12]:
enet_cv_model = ElasticNetCV(cv=10).fit(X_train, y_train)

In [13]:
enet_cv_model.alpha_

5230.7647364798695

In [14]:
enet_cv_model.intercept_

-38.5194055839429

In [15]:
enet_cv_model.coef_

array([ 0.62845434,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.09788752,  0.        ,
        0.27265769,  0.19270075,  0.00758665,  0.3106529 ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [16]:
# Final Modeli

In [17]:
enet_tuned_model = ElasticNet(alpha=enet_cv_model.alpha_).fit(X_train, y_train)

In [18]:
# Hata hesaplama

In [19]:
# Tahmin etme

In [20]:
y_pred = enet_tuned_model.predict(X_test)

In [21]:
np.sqrt(mean_squared_error(y_test, y_pred))

394.15280563218795

In [ ]:
#############################################

In [23]:
alphas = 10**np.linspace(10, -2, 100)*0.5

In [26]:
enet_cv_model_aciklama = ElasticNetCV(alphas=alphas, cv=10).fit(X_train, y_train)

In [27]:
enet_tuned_model_aciklama = ElasticNet(alpha=enet_cv_model_aciklama.alpha_).fit(X_train, y_train)

In [28]:
y_pred_aciklama = enet_tuned_model_aciklama.predict(X_test)

In [30]:
np.sqrt(mean_squared_error(y_test, y_pred_aciklama))

393.9753065850553

In [ ]:
# l1_ratio -> Bunun değeri 0(sıfır) olduğunda  l2 cezalandırılması, 1 olduğunda ise l1 cezalandırılması yapılır.
# Dolayısıyla 0 ile 1 arasında değişim olduğunda aslında cezalandırma metotlarının göreceli etkileri ifade edilmiş olur.
# Biz uygulamamız kapsamında ikisininde etkisinin aynı düzeyde olmasını istediğimizden dolayı buradaki l1_ratio oranı değerini 0.5 yani öntanımlı değeri olarak bırakmış olduk.  

In [ ]:
# alpha ve l1_ratio parametrelerini beraber düşünecek olursak l1_ratio için aranacak bir liste verdiğimizde - biz bir liste vermedik. normalde tunning bölümünde alpha için liste verebileceğimizi söylemiştik ve vermiştik. tunning bölümünde l1_ratio içinde liste verilebilir. İkisinin birbirlerine karşı olan durumlarında optimum sonucun ne zaman geldiğini inceleyebilmek adına yapılabilir.- l1_ratio için bir liste verildiğinde her bir l1_ratio değeri için farklı alpha değerleri olacaktır. Ki bu durumda bu alfalar ceza terimleri etkilerini modele yansıtmış olacaktır. 

In [22]:
?ElasticNet

Init signature:
ElasticNet(
    alpha=1.0,
    *,
    l1_ratio=0.5,
    fit_intercept=True,
    normalize=False,
    precompute=False,
    max_iter=1000,
    copy_X=True,
    tol=0.0001,
    warm_start=False,
    positive=False,
    random_state=None,
    selection='cyclic',
)
Docstring:     
Linear regression with combined L1 and L2 priors as regularizer.

Minimizes the objective function::

        1 / (2 * n_samples) * ||y - Xw||^2_2
        + alpha * l1_ratio * ||w||_1
        + 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2

If you are interested in controlling the L1 and L2 penalty
separately, keep in mind that this is equivalent to::

        a * L1 + b * L2

where::

        alpha = a + b and l1_ratio = a / (a + b)

The parameter l1_ratio corresponds to alpha in the glmnet R package while
alpha corresponds to the lambda parameter in glmnet. Specifically, l1_ratio
= 1 is the lasso penalty. Currently, l1_ratio <= 0.01 is not reliable,
unless you supply your own sequence of alpha.

Read

In [ ]:
# son