# ÇOKLU DOĞRUSAL REGRESYON

In [1]:
import pandas as pd 
df = pd.read_csv("verisetleri\Advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [2]:
X = df.drop('sales', axis=1)
y = df["sales"]

In [3]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [4]:
# pandas dataframe haline getirme
y = df[["sales"]]

In [5]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [6]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

## Stats Moles ile model kurmak

In [7]:
# StatsModel ile daha fazla bilgi alabileceğimiz doğrusal modellerin biraz daha yapısına uygun bazı sonuçlar elde edebiliriz
# Daha sonra scitlearn ile sadece katsayılar ile ilgilendiğimiz kısmıyla ilgili uygulama yapacağız.

In [10]:
!pip install statsmodels

In [9]:
import statsmodels.api as sm

In [10]:
# lm -> linear model, OLS -> Regresyon modelini kurmak için gerekli fonksiyon
lm = sm.OLS(y, X)

In [11]:
# Modeli kurma

In [12]:
model = lm.fit()

In [13]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Fri, 23 Oct 2020   Prob (F-statistic):                   2.43e-171
Time:                        20:42:17   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
# Bu çıktı önemlidir. 
# R-squared - R kare : Bağımsız değişkenlerin bağımlı değişkendeki değişkenliği açıklama yüzdesidir. 0.98 oldukça yüksek bir orandır. 
# Adj. R-squared : Düzeltilmiş R kare -> R kare değeri formülaysonu itibariyle verisetine ne kadar değişken eklenirse eklensin şişmeye meyillidir. Yani artmaya meyillidir. Bu durum modelde ilgili ya da ilgisiz bir çok değişken bulundurma eğilimine sebep olmaktadır. Yani bir veri bilimci, bir model geliştirici model geliştirme esnasında veri setine yeni değişkeler eklediğinde ve R kare değerinde bir artma gözlemlediğinde bu artmanın geçekten açılanabilirliğe katkı sağladığını düşünmektedir ki bu yanıltıcıdır. Çünkü R kare istatistiği formülasyonundan dolayı ne kadar değişken eklenirse o kadar şismektedir. İşte bu şişmenin önüne bir düzeltme işlemi gerçekleştirerek düzeltilmiş R kare değeri konulmuştur. Bu değer bize daha sağlıklı bir açıklanabilirlik oranı vermektedir.
# F-statistic : Modelin anlamlılığını test etmek için kullanılan istatistiktir. 
# Prob(F-statistic) : p-value değeri : 0.05 ten oldukça küçük değer ve bu modelin anlamlı olduğu bilgisini verir.
# coef : Bağımsız değişkenlerin katsayıları
# std err : standart hata
# t : t istatistiği
# P >|t| : P value değeri
# Bu değerler scitlearn de yoktur.
# Modelimiz anlamlı bir model 

## Scit Learn ile model kurma işlemi

In [17]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [18]:
model = lm.fit(X, y)

In [19]:
model.intercept_

array([2.93888937])

In [20]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [21]:
# statsmodel deki katsayıların değiştiğine dikkat ediniz.

# TAHMİN ETME

### Sales = 2.94 + TVx0.04 + radiox0.19 - newspaperx0.001

In [22]:
# 30 birim TV, 10 birim Radio, 40 birim Gazete harcaması sonucunda satışlar ne olur.

In [23]:
2.94 + 20*0.04 + 10*0.19 - 40*0.001

5.6000000000000005

In [70]:
yeni_veri = [[30],[10],[40]]
yeni_veri

[[30], [10], [40]]

In [76]:
import pandas as pd 
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [78]:
 model.predict(yeni_veri)

array([[6.15562918]])

## Başarısının değerlendirilmesi

In [79]:
from sklearn.metrics import mean_squared_error

In [80]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [82]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [86]:
MSE = mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [87]:
import numpy as np 
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

## MODEL TUNNING - MODEL DOĞRULAMA  

In [88]:
# Diğer bütün makina öğrenmesi modelleri için MODEL TUNNING işlemleri ele alınacak. Hiperparametre optimizasyonları gerçekleştirilecek
# Çoklu doğrusal regresyon modelinde bir hiperparametre olmadığından dolayı burada model tunning işleminden ziyade bir model doğrulama işlemi gerçekleştirmiş olacağız.


In [89]:
# Sınama Seti Yaklaşımı ve K-katlı Çapraz Doğrulama yöntemleri

In [90]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [91]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

## SINAMA SETİ

In [92]:
from sklearn.model_selection import train_test_split

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 99)

In [95]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [96]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [97]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [98]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [99]:
lm = LinearRegression()

In [100]:
model = lm.fit(X_train, y_train)

In [106]:
# Eğitim hatası - train hatası
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.723682482265075

In [108]:
# Test hatası
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4312783138301641

### Sınama yönteminde test ve train setleri değiştiğinde hatalarda değişmektedir. Aşağıda random_state=1 yaparak yani farklı veri setleri almasını sağlayarak yeniden model kurulduğunda hata ların değiştiği gözlemlenecektir. random_state = 99 sürekli aynı verilerin seçilmesini sağlamaktadır. 

In [153]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

In [155]:
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [158]:
# Eğitim hatası - train hatası
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.736902590147092

In [165]:
# Test hatası
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4113417558581587

In [166]:
# Bu sebepten dolayı k katlı doğrulama kullanılmaktadır.

## K KATLI CROSS VALIDATION

In [167]:
from sklearn.model_selection import cross_val_score

In [168]:
cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")

array([-1.62375953, -3.81875608, -3.43828142, -2.27748673, -7.25325414,
       -1.88303708, -2.80517715, -3.68594486, -1.12810834, -3.96330989])

In [169]:
# Yukarıda yapılan, train seti üzerinden 10 tane farklı hata hesaplandı. Yani train seti kendi içinde 10 parçaya bölündü 9 parça ile önce model kurulup 1 parçayla tahmin edildi ve bir hata elde edildi. Sonra diğer parça dışarda bırakıldı ve tekrar işlem yapıldı. Ve böylece 10 hata elde edildi.

In [170]:
# Sonraki adımda bunun ortalaması alınmalıdır. Değerler negatif olduğu için başına - eklenmelidir.

In [171]:
# CV mse - train için  
np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error"))

3.1877115209443567

In [172]:
# Ve böylece yukarıda ortalama hatayı elde ettik.

In [173]:
# CV rmse  - train için
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")))

1.7854163438661461

In [ ]:
# Bu değerin anlamı : K-katlı cv, tek başına sınama daki test ve train hatasının vermiş olduğu hatadan daha doğru bir hata ölçüsü verir. Yani veri doğrulanmıştır. Modeli doğrulamak demek bu demektir. İlkel test hatalarına göre valide edilmiş hatayı verir. CV doğrulanmış bir hata verir. 

In [174]:
# Karşılaştırma için : Sınama seti ve Cros Validation
# Burada bütün veri tek bir veri olarak kabul edilmektedir.
np.sqrt(np.mean(-cross_val_score(model, X, y, cv=10, scoring="neg_mean_squared_error")))

1.7492763126843378

In [175]:
# S O N